"""Annotate existing brick SVG and JSON assets for port-position debugging."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
	from . import debug
except ImportError:
	import debug


DEFAULT_ASSET_DIR = Path(__file__).resolve().parent / "brick_images"


def parse_args() -> argparse.Namespace:
	"""Parse command-line arguments for one asset-based debug render.

	Returns:
		Parsed command-line arguments.
	"""

	parser = argparse.ArgumentParser(
		description=(
			"Render one annotated debug image from an existing brick SVG and "
			"JSON pair generated by render_bricks.py."
		),
	)
	parser.add_argument(
		"brick_or_svg",
		help="Brick id, output stem, or explicit path to the source SVG asset.",
	)
	parser.add_argument(
		"--json",
		dest="json_path",
		type=Path,
		default=None,
		help="Optional explicit path to the source JSON sidecar.",
	)
	parser.add_argument(
		"--asset-dir",
		type=Path,
		default=DEFAULT_ASSET_DIR,
		help="Directory containing render_bricks.py SVG and JSON outputs.",
	)
	parser.add_argument(
		"--label",
		default=None,
		help="Optional title prefix for the annotated output.",
	)
	parser.add_argument(
		"--output-dir",
		type=Path,
		default=debug.DEFAULT_OUTPUT_DIR,
		help="Directory where the annotated SVG, PNG, and JSON files are written.",
	)
	return parser.parse_args()


def resolve_svg_path(brick_or_svg: str, asset_dir: Path) -> Path:
	"""Resolve one source SVG path from a stem or explicit SVG path.

	Args:
		brick_or_svg: Brick id, output stem, or explicit SVG path.
		asset_dir: Directory containing generated SVG assets.

	Returns:
		Resolved source SVG path.
	"""

	candidate = Path(brick_or_svg)
	if candidate.suffix.lower() == ".svg":
		return candidate

	if candidate.is_absolute() or len(candidate.parts) > 1:
		return candidate.with_suffix(".svg")

	return asset_dir / f"{brick_or_svg}.svg"


def resolve_json_path(svg_path: Path, explicit_json_path: Path | None) -> Path:
	"""Resolve the source JSON sidecar path for one SVG asset.

	Args:
		svg_path: Resolved source SVG path.
		explicit_json_path: Optional explicit JSON path.

	Returns:
		Resolved JSON sidecar path.
	"""

	return explicit_json_path if explicit_json_path is not None else svg_path.with_suffix(".json")


def load_port_geometry(json_path: Path) -> dict[str, dict[str, list[float]]]:
	"""Load port geometry from one render_bricks JSON sidecar.

	Args:
		json_path: Path to the generated brick JSON sidecar.

	Returns:
		Parsed port geometry mapping.

	Raises:
		ValueError: If the JSON payload is missing the expected ports object.
	"""

	payload = json.loads(json_path.read_text(encoding="utf-8"))
	ports = payload.get("ports")
	if not isinstance(ports, dict):
		raise ValueError(f"JSON file does not contain a valid ports mapping: {json_path}")
	return ports


def build_output_stem(svg_path: Path) -> str:
	"""Return the output filename stem for one annotated asset render.

	Args:
		svg_path: Path to the source SVG asset.

	Returns:
		Output filename stem without an extension.
	"""

	return f"{svg_path.stem}-ports"


def render_from_assets(
	svg_path: Path,
	json_path: Path,
	output_dir: Path,
	label: str | None = None,
) -> tuple[Path, Path, Path]:
	"""Render annotated debug outputs from an existing SVG and JSON pair.

	Args:
		svg_path: Path to the source brick SVG file.
		json_path: Path to the source brick JSON sidecar.
		output_dir: Directory where debug outputs should be written.
		label: Optional output label shown in the annotation title.

	Returns:
		Paths to the written annotated SVG, PNG, and JSON files.
	"""

	svg_text = svg_path.read_text(encoding="utf-8")
	port_geometry = load_port_geometry(json_path)
	brick_label = label or svg_path.stem
	annotated_svg = debug.annotate_svg(
		svg_text,
		brick_label,
		port_geometry,
	)

	output_dir.mkdir(parents=True, exist_ok=True)
	output_stem = build_output_stem(svg_path)
	svg_output_path = output_dir / f"{output_stem}.svg"
	png_output_path = output_dir / f"{output_stem}.png"
	json_output_path = output_dir / f"{output_stem}.json"

	svg_output_path.write_text(annotated_svg, encoding="utf-8")
	debug.write_debug_png(annotated_svg, png_output_path)
	json_output_path.write_text(json.dumps(port_geometry, indent=2, sort_keys=True), encoding="utf-8")
	return svg_output_path, png_output_path, json_output_path


def main() -> int:
	"""Run the asset-based debug render CLI.

	Returns:
		Process exit status code.
	"""

	args = parse_args()
	svg_path = resolve_svg_path(args.brick_or_svg, args.asset_dir)
	json_path = resolve_json_path(svg_path, args.json_path)
	svg_output_path, png_output_path, json_output_path = render_from_assets(
		svg_path=svg_path,
		json_path=json_path,
		output_dir=args.output_dir,
		label=args.label,
	)
	print(f"Annotated SVG written to {svg_output_path.resolve()}")
	print(f"Annotated PNG written to {png_output_path.resolve()}")
	print(f"Port geometry JSON written to {json_output_path.resolve()}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
